[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "0.20.0", features = ["methods"] }

[build-dependencies]
risc0-build = "0.20.0"

[package.metadata.risc0]
methods = ["guest"]
